name: Release

on:
  push:
    tags:
      - 'v*' # Triggers the workflow when a tag starting with 'v' is pushed

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build for multiple platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/passgen-linux-amd64 ./passgen.go
          GOOS=windows GOARCH=amd64 go build -o dist/passgen-windows-amd64.exe ./passgen.go
          GOOS=darwin GOARCH=amd64 go build -o dist/passgen-darwin-amd64 ./passgen.go

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/passgen-linux-amd64
            dist/passgen-windows-amd64.exe
            dist/passgen-darwin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
